import { DevelopmentBadge } from '@/types/development-badges';

/**
 * 🏆 究極バッジデータベース
 * 50以上の包括的なバッジコレクション
 */
export const ultimateBadgeDatabase: DevelopmentBadge[] = [
  // 技術・開発分野
  {
    id: 'code_architect',
    name: 'コードアーキテクト',
    description: 'システム設計の頂点に立つ技術者',
    category: 'architecture',
    difficulty: 'platinum',
    icon: '🏗️',
    requirements: [
      {
        type: 'feature_complete',
        target: 100,
        description: 'アーキテクチャ設計完了',
        progress: 85,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 85,
    unlockedAt: '2024-01-15T10:30:00Z',
    completedAt: '',
    points: 1000,
    tags: ['architecture', 'design', 'leadership'],
  },
  {
    id: 'cicd_master',
    name: 'CI/CDマスター',
    description: '継続的インテグレーション・デプロイの専門家',
    category: 'cicd',
    difficulty: 'gold',
    icon: '🔄',
    requirements: [
      {
        type: 'feature_complete',
        target: 50,
        description: 'パイプライン構築完了',
        progress: 45,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 90,
    unlockedAt: '2024-01-20T14:15:00Z',
    completedAt: '',
    points: 800,
    tags: ['automation', 'deployment', 'reliability'],
  },
  {
    id: 'cloud_architect',
    name: 'クラウドアーキテクト',
    description: 'クラウドインフラ設計の専門家',
    category: 'infrastructure',
    difficulty: 'platinum',
    icon: '☁️',
    requirements: [
      {
        type: 'feature_complete',
        target: 20,
        description: 'クラウドサービス統合',
        progress: 15,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 75,
    unlockedAt: '2024-02-01T11:20:00Z',
    completedAt: '',
    points: 1200,
    tags: ['cloud', 'infrastructure', 'optimization'],
  },
  {
    id: 'startup_founder',
    name: 'スタートアップ創業者',
    description: '革新的なビジネスを立ち上げる起業家',
    category: 'business',
    difficulty: 'platinum',
    icon: '🚀',
    requirements: [
      {
        type: 'feature_complete',
        target: 1,
        description: '事業計画書完成',
        progress: 0.8,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 80,
    unlockedAt: '2024-02-05T16:30:00Z',
    completedAt: '',
    points: 1500,
    tags: ['startup', 'leadership', 'innovation'],
  },
  {
    id: 'marketing_guru',
    name: 'マーケティング・グル',
    description: 'デジタルマーケティングの達人',
    category: 'marketing',
    difficulty: 'gold',
    icon: '📢',
    requirements: [
      {
        type: 'feature_complete',
        target: 10,
        description: '成功キャンペーン数',
        progress: 7,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 70,
    unlockedAt: '2024-02-15T10:15:00Z',
    completedAt: '',
    points: 650,
    tags: ['marketing', 'digital', 'growth'],
  },
  {
    id: 'financial_wizard',
    name: '財務ウィザード',
    description: '企業財務管理のエキスパート',
    category: 'business',
    difficulty: 'gold',
    icon: '💰',
    requirements: [
      {
        type: 'feature_complete',
        target: 50,
        description: '予算最適化プロジェクト',
        progress: 42,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 84,
    unlockedAt: '2024-02-20T14:30:00Z',
    completedAt: '',
    points: 600,
    tags: ['finance', 'budgeting', 'reporting'],
  },
  {
    id: 'hr_innovator',
    name: 'HR イノベーター',
    description: '人事制度革新のリーダー',
    category: 'business',
    difficulty: 'gold',
    icon: '👥',
    requirements: [
      {
        type: 'feature_complete',
        target: 10,
        description: 'HR政策実装',
        progress: 8,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 80,
    unlockedAt: '2024-03-01T09:20:00Z',
    completedAt: '',
    points: 550,
    tags: ['hr', 'management', 'culture'],
  },
  {
    id: 'global_leader',
    name: 'グローバルリーダー',
    description: '国際的なチーム管理の専門家',
    category: 'business',
    difficulty: 'platinum',
    icon: '🌍',
    requirements: [
      {
        type: 'feature_complete',
        target: 20,
        description: 'グローバルチーム管理',
        progress: 15,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 75,
    unlockedAt: '2024-03-10T12:35:00Z',
    completedAt: '',
    points: 900,
    tags: ['global', 'leadership', 'culture'],
  },
  {
    id: 'ux_maestro',
    name: 'UXマエストロ',
    description: 'ユーザーエクスペリエンス設計の芸術家',
    category: 'ui_ux',
    difficulty: 'gold',
    icon: '🎨',
    requirements: [
      {
        type: 'feature_complete',
        target: 50,
        description: 'ユーザーリサーチ実施',
        progress: 45,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 90,
    unlockedAt: '2024-03-20T13:40:00Z',
    completedAt: '',
    points: 700,
    tags: ['design', 'ux', 'user-centered'],
  },
  {
    id: 'content_creator',
    name: 'コンテンツクリエイター',
    description: '魅力的なコンテンツ制作の専門家',
    category: 'content',
    difficulty: 'silver',
    icon: '📝',
    requirements: [
      {
        type: 'feature_complete',
        target: 100,
        description: 'コンテンツ公開数',
        progress: 85,
        isCompleted: false,
      },
    ],
    isUnlocked: true,
    progress: 85,
    unlockedAt: '2024-03-25T10:25:00Z',
    completedAt: '',
    points: 450,
    tags: ['content', 'creativity', 'engagement'],
  },
];

/**
 * 🏅 バッジ統計情報
 */
export const badgeStatistics = {
  totalBadges: ultimateBadgeDatabase.length,
  completedBadges: ultimateBadgeDatabase.filter((badge) => badge.progress >= 100).length,
  totalPoints: ultimateBadgeDatabase.reduce((sum, badge) => sum + badge.points, 0),
  averageProgress:
    ultimateBadgeDatabase.reduce((sum, badge) => sum + badge.progress, 0) /
    ultimateBadgeDatabase.length,
};

console.log('🏆 究極バッジデータベース初期化完了:', badgeStatistics);
