// 月次概要ビューのサンプルデータ
const generateMonthlyOverviewData = (): MonthlyOverviewData => {
  return {
    metrics: {
      month: '2025年7月',
      year: 2025,
      totalBadges: 15,
      completedBadges: 4,
      inProgressBadges: 11,
      plannedHours: 180,
      actualHours: 142,
      efficiency: 78.9,
      completionRate: 26.7,
      averageConfidence: 82.3,
      streakDays: 23,
      topPerformingCategory: 'セキュリティ',
    },
    categories: [
      {
        name: 'セキュリティ',
        progress: 85,
        count: 4,
        completedCount: 2,
        icon: '🔐',
        color: 'red',
        estimatedHours: 60,
        actualHours: 52,
        efficiency: 86.7,
        topBadges: ['セキュリティ基礎', 'ネットワークセキュリティ'],
      },
      {
        name: 'デザイン・UX',
        progress: 60,
        count: 3,
        completedCount: 1,
        icon: '🎨',
        color: 'pink',
        estimatedHours: 40,
        actualHours: 28,
        efficiency: 70.0,
        topBadges: ['UXリサーチスペシャリスト'],
      },
      {
        name: 'プロジェクト管理',
        progress: 40,
        count: 4,
        completedCount: 1,
        icon: '📊',
        color: 'orange',
        estimatedHours: 35,
        actualHours: 32,
        efficiency: 91.4,
        topBadges: ['要件定義スペシャリスト'],
      },
      {
        name: '開発',
        progress: 75,
        count: 2,
        completedCount: 0,
        icon: '💻',
        color: 'blue',
        estimatedHours: 25,
        actualHours: 18,
        efficiency: 72.0,
        topBadges: [],
      },
      {
        name: 'AI・機械学習',
        progress: 30,
        count: 2,
        completedCount: 0,
        icon: '🤖',
        color: 'purple',
        estimatedHours: 20,
        actualHours: 12,
        efficiency: 60.0,
        topBadges: [],
      },
    ],
    trends: [
      {
        category: 'セキュリティ',
        previousMonth: 45,
        currentMonth: 85,
        trend: 'up',
        changePercentage: 88.9,
      },
      {
        category: 'デザイン・UX',
        previousMonth: 30,
        currentMonth: 60,
        trend: 'up',
        changePercentage: 100.0,
      },
      {
        category: 'プロジェクト管理',
        previousMonth: 50,
        currentMonth: 40,
        trend: 'down',
        changePercentage: -20.0,
      },
      {
        category: 'AI・機械学習',
        previousMonth: 25,
        currentMonth: 30,
        trend: 'up',
        changePercentage: 20.0,
      },
    ],
    achievements: [
      {
        badgeId: 'security-basics',
        badgeName: 'セキュリティ基礎',
        badgeEmoji: '🔐',
        category: 'セキュリティ',
        completedDate: '2025-07-02',
        hoursSpent: 12,
        difficulty: 'silver',
        impact: 'high',
      },
      {
        badgeId: 'network-security',
        badgeName: 'ネットワークセキュリティ',
        badgeEmoji: '🛡️',
        category: 'セキュリティ',
        completedDate: '2025-07-08',
        hoursSpent: 18,
        difficulty: 'gold',
        impact: 'high',
      },
      {
        badgeId: 'ux-researcher',
        badgeName: 'UXリサーチスペシャリスト',
        badgeEmoji: '🔍',
        category: 'デザイン・UX',
        completedDate: '2025-07-15',
        hoursSpent: 14,
        difficulty: 'gold',
        impact: 'medium',
      },
      {
        badgeId: 'requirements-specialist',
        badgeName: '要件定義スペシャリスト',
        badgeEmoji: '📊',
        category: 'プロジェクト管理',
        completedDate: '2025-07-22',
        hoursSpent: 16,
        difficulty: 'gold',
        impact: 'high',
      },
    ],
    weeklyBreakdown: [
      {
        weekNumber: 1,
        startDate: '2025-07-01',
        endDate: '2025-07-07',
        completedBadges: 1,
        hoursSpent: 38,
        efficiency: 82,
      },
      {
        weekNumber: 2,
        startDate: '2025-07-08',
        endDate: '2025-07-14',
        completedBadges: 1,
        hoursSpent: 42,
        efficiency: 78,
      },
      {
        weekNumber: 3,
        startDate: '2025-07-15',
        endDate: '2025-07-21',
        completedBadges: 1,
        hoursSpent: 35,
        efficiency: 75,
      },
      {
        weekNumber: 4,
        startDate: '2025-07-22',
        endDate: '2025-07-28',
        completedBadges: 1,
        hoursSpent: 27,
        efficiency: 81,
      },
    ],
    predictions: {
      nextMonthBadges: 6,
      nextMonthHours: 160,
      recommendedFocus: [
        'AI・機械学習分野の学習時間増加',
        'セキュリティ分野の継続的な深化',
        '開発スキルの実践的な応用',
      ],
    },
  };
};
