// バッジタイムラインビューのサンプルデータ生成
const generateTimelineSampleData = () => {
  const timelineBadges: TimelineBadge[] = [
    {
      id: 'security-basics',
      name: 'セキュリティ基礎',
      emoji: '🔐',
      category: 'セキュリティ',
      difficulty: 'silver',
      estimatedHours: 20,
      actualHours: 18,
      plannedStartDate: '2025-06-28',
      plannedEndDate: '2025-07-05',
      actualStartDate: '2025-06-28',
      actualEndDate: '2025-07-03',
      status: 'completed',
      progress: 100,
      confidence: 95,
      priority: 'high',
      dependencies: [],
      dependents: ['network-security', 'penetration-testing'],
      tags: ['基礎', 'セキュリティ'],
      description: 'サイバーセキュリティの基本概念と原則を学習',
      milestones: [
        {
          id: 'security-basics-theory',
          name: '理論学習完了',
          targetDate: '2025-07-01',
          isCompleted: true,
          completedDate: '2025-07-01',
        },
        {
          id: 'security-basics-practice',
          name: '実践演習完了',
          targetDate: '2025-07-03',
          isCompleted: true,
          completedDate: '2025-07-03',
        },
      ],
      risks: [],
    },
    {
      id: 'network-security',
      name: 'ネットワークセキュリティ',
      emoji: '🛡️',
      category: 'セキュリティ',
      difficulty: 'gold',
      estimatedHours: 25,
      actualHours: 22,
      plannedStartDate: '2025-07-06',
      plannedEndDate: '2025-07-15',
      actualStartDate: '2025-07-04',
      actualEndDate: '2025-07-12',
      status: 'completed',
      progress: 100,
      confidence: 88,
      priority: 'high',
      dependencies: ['security-basics'],
      dependents: ['penetration-testing'],
      tags: ['ネットワーク', 'セキュリティ'],
      description: 'ネットワークセキュリティの実装と監視',
      milestones: [
        {
          id: 'network-security-setup',
          name: 'セキュリティ環境構築',
          targetDate: '2025-07-08',
          isCompleted: true,
          completedDate: '2025-07-07',
        },
        {
          id: 'network-security-testing',
          name: 'セキュリティテスト実施',
          targetDate: '2025-07-12',
          isCompleted: true,
          completedDate: '2025-07-12',
        },
      ],
      risks: [],
    },
    {
      id: 'penetration-testing',
      name: 'ペネトレーションテスト',
      emoji: '🔍',
      category: 'セキュリティ',
      difficulty: 'platinum',
      estimatedHours: 35,
      actualHours: 28,
      plannedStartDate: '2025-07-16',
      plannedEndDate: '2025-07-30',
      actualStartDate: '2025-07-13',
      status: 'in_progress',
      progress: 75,
      confidence: 70,
      priority: 'high',
      dependencies: ['network-security'],
      dependents: ['security-specialist'],
      tags: ['ペネトレーションテスト', 'セキュリティ'],
      description: 'システムの脆弱性を評価するテスト技術',
      milestones: [
        {
          id: 'pentest-tools',
          name: 'ツール習得',
          targetDate: '2025-07-20',
          isCompleted: true,
          completedDate: '2025-07-18',
        },
        {
          id: 'pentest-practice',
          name: '実践テスト',
          targetDate: '2025-07-28',
          isCompleted: false,
        },
      ],
      risks: [
        {
          type: 'technical',
          level: 'medium',
          description: '高度なツールの習得に時間がかかる可能性',
          mitigation: 'オンライン講座と実践演習の組み合わせ',
        },
      ],
    },
    {
      id: 'ux-research',
      name: 'UXリサーチスペシャリスト',
      emoji: '🔍',
      category: 'デザイン・UX',
      difficulty: 'gold',
      estimatedHours: 30,
      actualHours: 25,
      plannedStartDate: '2025-07-08',
      plannedEndDate: '2025-07-20',
      actualStartDate: '2025-07-10',
      actualEndDate: '2025-07-18',
      status: 'completed',
      progress: 100,
      confidence: 92,
      priority: 'medium',
      dependencies: [],
      dependents: ['ui-designer'],
      tags: ['UX', 'リサーチ'],
      description: 'ユーザー調査とUXリサーチ手法の習得',
      milestones: [
        {
          id: 'ux-theory',
          name: 'UX理論学習',
          targetDate: '2025-07-12',
          isCompleted: true,
          completedDate: '2025-07-11',
        },
        {
          id: 'ux-interviews',
          name: 'ユーザーインタビュー実施',
          targetDate: '2025-07-18',
          isCompleted: true,
          completedDate: '2025-07-17',
        },
      ],
      risks: [],
    },
    {
      id: 'ai-fundamentals',
      name: 'AI基礎',
      emoji: '🤖',
      category: 'AI・機械学習',
      difficulty: 'gold',
      estimatedHours: 40,
      actualHours: 12,
      plannedStartDate: '2025-07-22',
      plannedEndDate: '2025-08-10',
      actualStartDate: '2025-07-25',
      status: 'in_progress',
      progress: 25,
      confidence: 60,
      priority: 'medium',
      dependencies: [],
      dependents: ['machine-learning'],
      tags: ['AI', '機械学習'],
      description: 'AI・機械学習の基礎理論と実装',
      milestones: [
        {
          id: 'ai-python-setup',
          name: 'Python環境構築',
          targetDate: '2025-07-26',
          isCompleted: true,
          completedDate: '2025-07-26',
        },
        {
          id: 'ai-theory',
          name: 'AI理論学習',
          targetDate: '2025-08-02',
          isCompleted: false,
        },
        {
          id: 'ai-practice',
          name: '実践プロジェクト',
          targetDate: '2025-08-08',
          isCompleted: false,
        },
      ],
      risks: [
        {
          type: 'technical',
          level: 'high',
          description: '数学的基礎知識の不足により進捗遅延の可能性',
          mitigation: '数学基礎の並行学習と専門書の活用',
        },
        {
          type: 'schedule',
          level: 'medium',
          description: '他の優先タスクにより学習時間が不足',
          mitigation: '学習スケジュールの見直しと優先度調整',
        },
      ],
    },
    {
      id: 'requirements-analysis',
      name: '要件定義スペシャリスト',
      emoji: '📊',
      category: 'プロジェクト管理',
      difficulty: 'gold',
      estimatedHours: 25,
      actualHours: 20,
      plannedStartDate: '2025-07-15',
      plannedEndDate: '2025-07-25',
      actualStartDate: '2025-07-16',
      actualEndDate: '2025-07-24',
      status: 'completed',
      progress: 100,
      confidence: 90,
      priority: 'high',
      dependencies: [],
      dependents: ['project-management'],
      tags: ['要件定義', 'PM'],
      description: 'システム要件の分析と定義のスキル習得',
      milestones: [
        {
          id: 'req-methodology',
          name: '要件定義手法学習',
          targetDate: '2025-07-19',
          isCompleted: true,
          completedDate: '2025-07-18',
        },
        {
          id: 'req-documentation',
          name: '要件書作成実践',
          targetDate: '2025-07-24',
          isCompleted: true,
          completedDate: '2025-07-23',
        },
      ],
      risks: [],
    },
  ];

  const timelineEvents: TimelineEvent[] = [
    {
      id: 'event-1',
      type: 'badge_start',
      date: '2025-06-28',
      badgeId: 'security-basics',
      title: 'セキュリティ基礎学習開始',
      description: 'サイバーセキュリティの基本概念学習を開始',
      importance: 'high',
      status: 'actual',
    },
    {
      id: 'event-2',
      type: 'milestone',
      date: '2025-07-01',
      badgeId: 'security-basics',
      title: 'セキュリティ理論学習完了',
      description: 'セキュリティ基礎理論の学習を完了',
      importance: 'medium',
      status: 'actual',
    },
    {
      id: 'event-3',
      type: 'badge_complete',
      date: '2025-07-03',
      badgeId: 'security-basics',
      title: 'セキュリティ基礎バッジ獲得',
      description: 'セキュリティ基礎バッジを予定より2日早く獲得',
      importance: 'high',
      status: 'actual',
    },
    {
      id: 'event-4',
      type: 'dependency',
      date: '2025-07-04',
      badgeId: 'network-security',
      title: 'ネットワークセキュリティ学習開始',
      description: 'セキュリティ基礎完了により依存関係解除、学習開始',
      importance: 'medium',
      status: 'actual',
      relatedBadges: ['security-basics'],
    },
    {
      id: 'event-5',
      type: 'risk',
      date: '2025-07-25',
      badgeId: 'ai-fundamentals',
      title: 'AI基礎学習で遅延リスク発生',
      description: '数学的基礎知識不足により進捗遅延の可能性',
      importance: 'critical',
      status: 'actual',
    },
    {
      id: 'event-6',
      type: 'milestone',
      date: '2025-08-01',
      badgeId: 'penetration-testing',
      title: 'ペネトレーションテスト実践予定',
      description: '実際のシステムでのペネトレーションテスト実施予定',
      importance: 'high',
      status: 'planned',
    },
  ];

  return { timelineBadges, timelineEvents };
};

export const TimelineViewComplete: React.FC = () => {
  const [filter, setFilter] = useState<TimelineFilter>({
    // ...
  });

  return (
    // ... existing JSX
  );
};
