import { MusicGenre } from './GenreSelector';

export const musicGenres: MusicGenre[] = [
  {
    id: "balanced",
    name: "バランス",
    baseTempo: 120,
    instruments: ["piano", "strings"],
    description: "バランスの取れた食事の時",
    keySignature: "C",
  },
  {
    id: "meiwa",
    name: "明和電機",
    baseTempo: 120,
    instruments: ["8bit", "chip"],
    description: "8bit風のチップチューン・明和電機風",
    keySignature: "C",
  },
  {
    id: "rock",
    name: "ロック",
    baseTempo: 140,
    instruments: ["distortion", "drums", "bass"],
    description: "パワフルなロックサウンド",
    keySignature: "A",
  },
  {
    id: "techno",
    name: "テクノ",
    baseTempo: 128,
    instruments: ["synth", "electronic"],
    description: "明和電機風の電子音楽",
    keySignature: "Am",
  },
  {
    id: "classical",
    name: "クラシック",
    baseTempo: 80,
    instruments: ["strings", "piano", "orchestra"],
    description: "優雅なクラシック",
    keySignature: "G",
  },
  {
    id: "japanese",
    name: "和楽器",
    baseTempo: 100,
    instruments: ["shamisen", "taiko", "koto"],
    description: "明和電機風の機械音",
    keySignature: "Dm",
  },
  {
    id: "jazz",
    name: "ジャズ",
    baseTempo: 110,
    instruments: ["saxophone", "piano", "bass"],
    description: "スウィングジャズ",
    keySignature: "F",
  },
  {
    id: "ambient",
    name: "アンビエント",
    baseTempo: 60,
    instruments: ["pad", "atmosphere"],
    description: "環境音楽",
    keySignature: "C",
  },
  {
    id: "custom",
    name: "カスタム",
    baseTempo: 120,
    instruments: ["piano"],
    description: "ユーザー設定",
    keySignature: "C",
  },
];
