/**
 * 🌟 拡張バッジカテゴリシステム
 * 12週間計画と全分野を網羅する追加バッジ定義
 */

import { ComprehensiveBadge } from '@/types/comprehensive-badge-categories';

/**
 * 🎯 Week 5-8 新規バッジ群
 */
export const WEEK_5_8_BADGES: ComprehensiveBadge[] = [
  // Week 5: アクセシビリティ & UX
  {
    id: 'accessibility-champion',
    name: '♿ アクセシビリティチャンピオン',
    description: 'Webアクセシビリティとインクルーシブデザインの専門家',
    category: 'accessibility',
    difficulty: 'gold',
    icon: '♿',
    points: 350,
    requirements: [
      {
        type: 'assessments_passed',
        target: '15',
        current: '0',
        description: 'WCAG 2.1 AA準拠テスト15件',
        pageIntegration: 'accessibility-testing',
      },
      {
        type: 'skills_demonstrated',
        target: '10',
        current: '0',
        description: 'アクセシビリティ改善10件実装',
      },
      {
        type: 'content_created',
        target: '5',
        current: '0',
        description: 'アクセシビリティガイドライン5件作成',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'WCAG準拠テスト',
    prerequisites: ['cybersecurity-specialist'],
    rewards: ['インクルーシブデザイン', 'ユニバーサルアクセス'],
    estimatedHours: 15,
    relatedPages: ['accessibility-dashboard', 'ux-research', 'design-system'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'ux-research-specialist',
    name: '🔍 UXリサーチスペシャリスト',
    description: 'ユーザー体験研究とデータドリブンデザインの専門家',
    category: 'user-research',
    difficulty: 'platinum',
    icon: '🔍',
    points: 420,
    requirements: [
      {
        type: 'data_analyzed',
        target: '30',
        current: '0',
        description: 'ユーザー行動データ30件分析',
        pageIntegration: 'analytics-dashboard',
      },
      {
        type: 'content_created',
        target: '10',
        current: '0',
        description: 'UXリサーチレポート10件作成',
      },
      {
        type: 'assessments_passed',
        target: '8',
        current: '0',
        description: 'ユーザビリティテスト8件実施',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'ユーザー行動分析',
    prerequisites: [],
    rewards: ['データドリブンデザイン', 'ユーザーインサイト'],
    estimatedHours: 25,
    relatedPages: ['ux-research', 'analytics', 'user-testing'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // Week 6: オペレーショナルエクセレンス
  {
    id: 'operational-excellence',
    name: '⚙️ オペレーショナルエクセレンス',
    description: '運用効率化とプロセス最適化の専門家',
    category: 'monitoring',
    difficulty: 'platinum',
    icon: '⚙️',
    points: 450,
    requirements: [
      {
        type: 'improvements_made',
        target: '20',
        current: '0',
        description: 'プロセス改善20件実施',
        pageIntegration: 'operations-dashboard',
      },
      {
        type: 'time_spent',
        target: '50',
        current: '0',
        description: '運用監視50時間',
      },
      {
        type: 'innovations_implemented',
        target: '5',
        current: '0',
        description: '運用自動化5件導入',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'プロセス改善実装',
    prerequisites: ['cybersecurity-specialist'],
    rewards: ['運用効率化', 'プロセス最適化'],
    estimatedHours: 30,
    relatedPages: ['system-monitoring', 'automation-rules', 'performance-optimization'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'performance-optimization-master',
    name: '⚡ パフォーマンス最適化マスター',
    description: 'システムパフォーマンス向上とボトルネック解決の専門家',
    category: 'performance',
    difficulty: 'gold',
    icon: '⚡',
    points: 380,
    requirements: [
      {
        type: 'problems_solved',
        target: '25',
        current: '0',
        description: 'パフォーマンス問題25件解決',
        pageIntegration: 'performance-monitoring',
      },
      {
        type: 'improvements_made',
        target: '15',
        current: '0',
        description: 'パフォーマンス改善15件実施',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'ボトルネック解決',
    prerequisites: [],
    rewards: ['高速化技術', 'パフォーマンス監視'],
    estimatedHours: 20,
    relatedPages: ['performance-optimization', 'monitoring', 'scaling'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // Week 7: フルスタック & データサイエンス
  {
    id: 'full-stack-architect',
    name: '🏗️ フルスタックアーキテクト',
    description: 'エンドツーエンド システム設計とアーキテクチャの専門家',
    category: 'architecture',
    difficulty: 'legendary',
    icon: '🏗️',
    points: 550,
    requirements: [
      {
        type: 'projects_created',
        target: '5',
        current: '0',
        description: 'フルスタックアプリ5個構築',
        pageIntegration: 'system-design',
      },
      {
        type: 'skills_demonstrated',
        target: '12',
        current: '0',
        description: 'アーキテクチャパターン12種習得',
      },
      {
        type: 'assessments_passed',
        target: '8',
        current: '0',
        description: 'システム設計レビュー8件',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'マイクロサービス設計',
    prerequisites: ['cybersecurity-specialist', 'operational-excellence'],
    rewards: ['システム全体設計', 'アーキテクチャ最適化'],
    estimatedHours: 40,
    relatedPages: ['system-design', 'development-badges', 'infrastructure'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'data-science-expert',
    name: '📊 データサイエンスエキスパート',
    description: '機械学習とビッグデータ分析の専門家',
    category: 'ai-ml',
    difficulty: 'platinum',
    icon: '📊',
    points: 480,
    requirements: [
      {
        type: 'data_analyzed',
        target: '100',
        current: '0',
        description: 'データセット100件分析',
        pageIntegration: 'data-visualization',
      },
      {
        type: 'projects_created',
        target: '8',
        current: '0',
        description: 'MLモデル8個構築',
      },
      {
        type: 'innovations_implemented',
        target: '5',
        current: '0',
        description: 'AI機能5個実装',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: '機械学習モデル構築',
    prerequisites: [],
    rewards: ['データ分析力', 'AI実装技術'],
    estimatedHours: 35,
    relatedPages: ['data-visualization', 'ai-dashboard', 'analytics'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // Week 8: 最先端技術領域
  {
    id: 'ai-ethics-specialist',
    name: '🤖 AI倫理スペシャリスト',
    description: '人工知能の倫理的活用と責任あるAI開発の専門家',
    category: 'ai-ml',
    difficulty: 'legendary',
    icon: '🤖',
    points: 500,
    requirements: [
      {
        type: 'content_created',
        target: '10',
        current: '0',
        description: 'AI倫理ガイドライン10件作成',
        pageIntegration: 'ai-ethics-dashboard',
      },
      {
        type: 'assessments_passed',
        target: '5',
        current: '0',
        description: 'AIバイアス監査5件実施',
      },
      {
        type: 'innovations_implemented',
        target: '3',
        current: '0',
        description: '倫理的AI機能3個実装',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'AI倫理フレームワーク',
    prerequisites: ['data-science-expert'],
    rewards: ['責任あるAI', '倫理的判断力'],
    estimatedHours: 45,
    relatedPages: ['ai-dashboard', 'ethics-compliance', 'governance'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'blockchain-developer',
    name: '⛓️ ブロックチェーン開発者',
    description: '分散台帳技術とWeb3開発の専門家',
    category: 'development',
    difficulty: 'platinum',
    icon: '⛓️',
    points: 450,
    requirements: [
      {
        type: 'projects_created',
        target: '5',
        current: '0',
        description: 'ブロックチェーンアプリ5個開発',
        pageIntegration: 'blockchain-dashboard',
      },
      {
        type: 'skills_demonstrated',
        target: '8',
        current: '0',
        description: 'スマートコントラクト8種実装',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'スマートコントラクト開発',
    prerequisites: ['cybersecurity-specialist'],
    rewards: ['Web3技術', '分散システム'],
    estimatedHours: 38,
    relatedPages: ['blockchain-dashboard', 'crypto-wallet', 'defi-platform'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'quantum-computing-researcher',
    name: '🔬 量子コンピューティング研究者',
    description: '量子計算と量子アルゴリズムの専門家',
    category: 'research',
    difficulty: 'legendary',
    icon: '🔬',
    points: 600,
    requirements: [
      {
        type: 'content_created',
        target: '8',
        current: '0',
        description: '量子アルゴリズム8個実装',
        pageIntegration: 'quantum-lab',
      },
      {
        type: 'time_spent',
        target: '80',
        current: '0',
        description: '量子プログラミング80時間',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: '量子アルゴリズム実装',
    prerequisites: ['data-science-expert'],
    rewards: ['量子計算技術', '次世代コンピューティング'],
    estimatedHours: 50,
    relatedPages: ['quantum-lab', 'research-dashboard', 'simulation'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'cloud-architect-master',
    name: '☁️ クラウドアーキテクトマスター',
    description: 'マルチクラウド戦略とクラウドネイティブ設計の専門家',
    category: 'infrastructure',
    difficulty: 'platinum',
    icon: '☁️',
    points: 480,
    requirements: [
      {
        type: 'projects_created',
        target: '10',
        current: '0',
        description: 'クラウドアーキテクチャ10個設計',
        pageIntegration: 'cloud-dashboard',
      },
      {
        type: 'assessments_passed',
        target: '6',
        current: '0',
        description: 'クラウド認定6件取得',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'マルチクラウド設計',
    prerequisites: ['full-stack-architect'],
    rewards: ['クラウド戦略', 'スケーラブル設計'],
    estimatedHours: 32,
    relatedPages: ['cloud-dashboard', 'infrastructure', 'scaling'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  {
    id: 'sustainable-tech-advocate',
    name: '🌱 サステナブルテック推進者',
    description: '持続可能な技術とグリーンIT実践の専門家',
    category: 'social-contribution',
    difficulty: 'gold',
    icon: '🌱',
    points: 350,
    requirements: [
      {
        type: 'improvements_made',
        target: '15',
        current: '0',
        description: 'エネルギー効率改善15件',
        pageIntegration: 'sustainability-dashboard',
      },
      {
        type: 'content_created',
        target: '8',
        current: '0',
        description: 'グリーンIT指針8件策定',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'グリーンIT実装',
    prerequisites: [],
    rewards: ['持続可能技術', '環境配慮設計'],
    estimatedHours: 25,
    relatedPages: ['sustainability-dashboard', 'energy-monitoring', 'green-metrics'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },
];

/**
 * 🎓 追加専門分野バッジ群
 * ユーザー要求の全分野を網羅
 */
export const ADDITIONAL_SPECIALTY_BADGES: ComprehensiveBadge[] = [
  // 法務・コンプライアンス
  {
    id: 'legal-compliance-specialist',
    name: '⚖️ 法務コンプライアンススペシャリスト',
    description: '法的要件とリスク管理の専門家',
    category: 'legal',
    difficulty: 'platinum',
    icon: '⚖️',
    points: 420,
    requirements: [
      {
        type: 'assessments_passed',
        target: '12',
        current: '0',
        description: 'コンプライアンス監査12件',
        pageIntegration: 'legal-dashboard',
      },
      {
        type: 'content_created',
        target: '10',
        current: '0',
        description: '法務ガイドライン10件作成',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'リスク評価フレームワーク',
    prerequisites: [],
    rewards: ['法的リスク管理', 'コンプライアンス体制'],
    estimatedHours: 35,
    relatedPages: ['legal-dashboard', 'compliance-monitoring', 'risk-management'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 人事・労務
  {
    id: 'hr-strategic-partner',
    name: '👥 HR戦略パートナー',
    description: '人材戦略と組織開発の専門家',
    category: 'hr',
    difficulty: 'gold',
    icon: '👥',
    points: 380,
    requirements: [
      {
        type: 'data_analyzed',
        target: '20',
        current: '0',
        description: '人材データ20件分析',
        pageIntegration: 'hr-dashboard',
      },
      {
        type: 'content_created',
        target: '8',
        current: '0',
        description: '人材育成プログラム8件設計',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: '人材戦略策定',
    prerequisites: [],
    rewards: ['人材開発', '組織最適化'],
    estimatedHours: 30,
    relatedPages: ['hr-dashboard', 'team-management', 'skill-mapping'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 営業・マーケティング
  {
    id: 'sales-growth-hacker',
    name: '📈 セールスグロースハッカー',
    description: '営業戦略とグロースハッキングの専門家',
    category: 'sales',
    difficulty: 'platinum',
    icon: '📈',
    points: 450,
    requirements: [
      {
        type: 'goals_achieved',
        target: '15',
        current: '0',
        description: '売上目標15件達成',
        pageIntegration: 'sales-dashboard',
      },
      {
        type: 'innovations_implemented',
        target: '8',
        current: '0',
        description: 'グロースハック手法8個実装',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'セールスファネル最適化',
    prerequisites: ['marketing-strategist'],
    rewards: ['売上成長', 'マーケット拡大'],
    estimatedHours: 40,
    relatedPages: ['sales-dashboard', 'marketing-automation', 'crm-system'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 経済・金融
  {
    id: 'fintech-innovator',
    name: '💳 FinTechイノベーター',
    description: '金融技術とデジタル決済の専門家',
    category: 'finance',
    difficulty: 'legendary',
    icon: '💳',
    points: 520,
    requirements: [
      {
        type: 'projects_created',
        target: '5',
        current: '0',
        description: 'FinTechアプリ5個開発',
        pageIntegration: 'fintech-dashboard',
      },
      {
        type: 'innovations_implemented',
        target: '10',
        current: '0',
        description: '決済イノベーション10件',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'デジタル決済システム',
    prerequisites: ['financial-analyst', 'blockchain-developer'],
    rewards: ['金融革新', 'デジタル経済'],
    estimatedHours: 45,
    relatedPages: ['fintech-dashboard', 'payment-gateway', 'digital-banking'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 文化・芸術
  {
    id: 'digital-artist-curator',
    name: '🎨 デジタルアーティスト・キュレーター',
    description: 'デジタルアートとクリエイティブテクノロジーの専門家',
    category: 'arts',
    difficulty: 'gold',
    icon: '🎨',
    points: 360,
    requirements: [
      {
        type: 'content_created',
        target: '20',
        current: '0',
        description: 'デジタルアート作品20点制作',
        pageIntegration: 'digital-gallery',
      },
      {
        type: 'collaborations',
        target: '10',
        current: '0',
        description: 'アーティストコラボ10件',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'NFTアート展開',
    prerequisites: [],
    rewards: ['クリエイティブ技術', 'アート思考'],
    estimatedHours: 35,
    relatedPages: ['digital-gallery', 'nft-marketplace', 'creative-tools'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 言語・国際化
  {
    id: 'multilingual-localization-expert',
    name: '🌐 多言語ローカライゼーションエキスパート',
    description: '国際化とローカライゼーション戦略の専門家',
    category: 'language',
    difficulty: 'platinum',
    icon: '🌐',
    points: 400,
    requirements: [
      {
        type: 'projects_created',
        target: '8',
        current: '0',
        description: '多言語対応プロジェクト8件',
        pageIntegration: 'i18n-dashboard',
      },
      {
        type: 'skills_demonstrated',
        target: '6',
        current: '0',
        description: '言語技術6種習得',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'グローバル展開戦略',
    prerequisites: [],
    rewards: ['国際対応力', 'グローバル思考'],
    estimatedHours: 32,
    relatedPages: ['i18n-dashboard', 'translation-tools', 'global-market'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 出版・編集
  {
    id: 'digital-publishing-master',
    name: '📚 デジタル出版マスター',
    description: 'デジタルコンテンツ制作と配信プラットフォームの専門家',
    category: 'publishing',
    difficulty: 'gold',
    icon: '📚',
    points: 370,
    requirements: [
      {
        type: 'content_created',
        target: '15',
        current: '0',
        description: 'デジタル出版物15冊制作',
        pageIntegration: 'publishing-platform',
      },
      {
        type: 'innovations_implemented',
        target: '5',
        current: '0',
        description: '配信技術5個実装',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'インタラクティブ出版',
    prerequisites: ['digital-artist-curator'],
    rewards: ['コンテンツ戦略', 'デジタル配信'],
    estimatedHours: 28,
    relatedPages: ['publishing-platform', 'content-management', 'reader-analytics'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 哲学・倫理
  {
    id: 'tech-philosopher',
    name: '🤔 テクノロジー哲学者',
    description: '技術哲学と倫理的思考の専門家',
    category: 'philosophy',
    difficulty: 'platinum',
    icon: '🤔',
    points: 430,
    requirements: [
      {
        type: 'content_created',
        target: '12',
        current: '0',
        description: '技術哲学論文12本執筆',
        pageIntegration: 'philosophy-journal',
      },
      {
        type: 'presentations_given',
        target: '8',
        current: '0',
        description: '倫理的思考セミナー8回開催',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: '技術倫理フレームワーク',
    prerequisites: ['ai-ethics-specialist'],
    rewards: ['哲学的思考', '倫理的判断'],
    estimatedHours: 40,
    relatedPages: ['philosophy-journal', 'ethics-framework', 'thought-leadership'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },

  // 宗教・スピリチュアル
  {
    id: 'digital-spirituality-guide',
    name: '🕊️ デジタルスピリチュアリティガイド',
    description: 'デジタル時代の精神性とウェルビーイングの専門家',
    category: 'religion',
    difficulty: 'gold',
    icon: '🕊️',
    points: 320,
    requirements: [
      {
        type: 'content_created',
        target: '10',
        current: '0',
        description: 'スピリチュアルガイド10件作成',
        pageIntegration: 'wellness-platform',
      },
      {
        type: 'collaborations',
        target: '5',
        current: '0',
        description: 'ウェルビーイングプログラム5件',
      },
    ],
    isUnlocked: false,
    progress: 0,
    nextMilestone: 'デジタルマインドフルネス',
    prerequisites: [],
    rewards: ['精神的バランス', 'ウェルビーイング'],
    estimatedHours: 25,
    relatedPages: ['wellness-platform', 'meditation-app', 'mindfulness-tools'],
    syncData: {
      lastUpdated: new Date(),
      pageActivities: {},
      crossPageProgress: {},
      integrationScore: 0,
      synchronizedFeatures: [],
    },
  },
];

/**
 * 🚀 全拡張バッジコレクション
 */
export const ALL_EXTENDED_BADGES: ComprehensiveBadge[] = [
  ...WEEK_5_8_BADGES,
  ...ADDITIONAL_SPECIALTY_BADGES,
];

/**
 * 📊 拡張バッジ統計
 */
export const EXTENDED_BADGE_STATISTICS = {
  week5to8Badges: WEEK_5_8_BADGES.length,
  additionalSpecialtyBadges: ADDITIONAL_SPECIALTY_BADGES.length,
  totalExtendedBadges: ALL_EXTENDED_BADGES.length,
  totalPoints: ALL_EXTENDED_BADGES.reduce((sum, badge) => sum + badge.points, 0),
  totalEstimatedHours: ALL_EXTENDED_BADGES.reduce((sum, badge) => sum + badge.estimatedHours, 0),
  difficultyDistribution: {
    legendary: ALL_EXTENDED_BADGES.filter((b) => b.difficulty === 'legendary').length,
    platinum: ALL_EXTENDED_BADGES.filter((b) => b.difficulty === 'platinum').length,
    gold: ALL_EXTENDED_BADGES.filter((b) => b.difficulty === 'gold').length,
    silver: ALL_EXTENDED_BADGES.filter((b) => b.difficulty === 'silver').length,
    bronze: ALL_EXTENDED_BADGES.filter((b) => b.difficulty === 'bronze').length,
  },
  categoryDistribution: ALL_EXTENDED_BADGES.reduce(
    (acc, badge) => {
      acc[badge.category] = (acc[badge.category] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  ),
} as const;
