import { USE_MOCK_DATA } from '@/services/api/apiConfig';

export type FeatureStatus =
  // New granular flow
  | 'planning' // 計画中
  | 'designing' // 設計中
  | 'developing' // 開発中
  | 'unit_testing' // 単体テスト中（ユニット）
  | 'integration_testing' // 結合テスト中（ローカル手動操作/e2e）
  | 'system_testing' // 総合テスト中（本番環境での操作）
  | 'documenting' // ドキュメント整備中
  | 'review' // 確認中（ドキュメントレビュー）
  | 'release_pending' // リリース待ち
  | 'complete' // 完成
  // Back-compat (will be mapped)
  | 'in_progress'
  | 'planned'
  | 'testing'
  | 'docs';

export interface Feature {
  id: string;
  name: string;
  path: string; // leading slash path prefix
  category: string;
  description?: string;
  status: FeatureStatus;
  requiresRealAPI?: boolean;
  priority?: 'P0' | 'P1' | 'P2' | 'P3';
  // 無効化（全ユーザー/管理者含めアクセス不可・メニュー非表示）
  disabled?: boolean;
  // 目標リリース日（例: 2025-09-01）
  targetRelease?: string;
}

export const featuresRegistry: Feature[] = [
  {
    id: 'home',
    name: 'ホーム',
    path: '/',
    category: 'コア',
    description: 'ホームとダッシュボード（タブ切替）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'sitemap',
    name: 'サイトマップ',
    path: '/sitemap',
    category: 'コア',
    description: '全機能一覧・使用ガイド・新機能案内',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'dashboard',
    name: '統合ダッシュボード',
    path: '/integrated-dashboard',
    category: 'コア',
    description: 'プロジェクト・タスク統合ビュー',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'tasks',
    name: 'タスク管理センター',
    path: '/tasks',
    category: '仕事',
    description: '統合タスク管理',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'calendar',
    name: 'カレンダー',
    path: '/calendar',
    category: '仕事',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'work-pattern-settings',
    name: '勤務パターン設定',
    path: '/work-pattern-settings',
    category: '勤怠',
    description: '勤務時間・休憩・残業設定',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'worktime-entry',
    name: '勤怠入力',
    path: '/worktime-entry',
    category: '勤怠',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'worktime-form',
    name: '📝 勤怠フォーム',
    path: '/worktime-form',
    category: '勤怠',
    description: '詳細な勤怠情報入力フォーム',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'realtime-clock',
    name: 'リアルタイム勤怠',
    path: '/realtime-clock',
    category: '勤怠',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'monthly-timesheet',
    name: '月次勤怠集計',
    path: '/monthly-timesheet',
    category: '勤怠',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'daily-work-visualization',
    name: '📊 日次勤務可視化',
    path: '/daily-work-visualization',
    category: '勤怠',
    description: '当日の勤務/休憩/残業を可視化',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'reports',
    name: '勤怠レポート',
    path: '/reports',
    category: '勤怠',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'work-time',
    name: '勤怠管理（一覧）',
    path: '/work-time',
    category: '勤怠',
    description: '勤怠の概要/エントリへのハブ',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'work-time-reports',
    name: '勤怠レポート（ホーム）',
    path: '/work-time-reports',
    category: '勤怠',
    description: 'ホームからのレポートショートカット',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'approval-workflow',
    name: '承認ワークフロー',
    path: '/approval-workflow',
    category: '勤怠',
    description: '勤怠データの承認申請・承認',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'ai-assistant',
    name: 'AI秘書',
    path: '/ai-assistant',
    category: 'AI',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'adhd-integrated-life',
    name: '🧠 ADHD統合ライフ',
    path: '/adhd-integrated-life',
    category: 'コア',
    description: 'ADHD/ASD特化型生活支援システム',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'adhd-integrated-life-page',
    name: '🧠 ADHD統合ライフ（ページ）',
    path: '/adhd-integrated-life-page',
    category: 'コア',
    description: 'ADHD/ASD特化型生活支援ページ',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'assessments',
    name: '自己診断',
    path: '/assessments',
    category: '診断',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'adhd-cognitive-assessment',
    name: '🧪 認知機能評価',
    path: '/adhd-cognitive-assessment',
    category: 'コア',
    description: 'WEIS準拠の科学的認知機能測定',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'learning',
    name: '学習ハブ',
    path: '/learning',
    category: '学習',
    status: 'planned',
    requiresRealAPI: false,
  },
  {
    id: 'analytics',
    name: 'アナリティクス',
    path: '/analytics',
    category: '分析',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'quadrant-dashboard',
    name: '🎯 4象限マトリックス',
    path: '/quadrant-dashboard',
    category: '分析',
    description: 'AI駆動タスク分類・生産性分析',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'accessibility-audit',
    name: '♿ アクセシビリティ監査',
    path: '/accessibility-audit',
    category: '品質',
    description: 'WCAG 2.1 準拠監査と改善提案',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'advanced-performance-monitoring',
    name: '🚀 高度パフォーマンス監視',
    path: '/advanced-performance-monitoring',
    category: '品質',
    description: 'Lighthouse 監視とリアルタイム性能分析',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'quality-dashboard',
    name: '品質ダッシュボード',
    path: '/quality-dashboard',
    category: '品質',
    status: 'planned',
    requiresRealAPI: false,
  },
  {
    id: 'production-optimization',
    name: '🏭 本番環境最適化',
    path: '/production-optimization',
    category: '運用',
    description: 'CDN・キャッシュ戦略・監視最適化',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'mobile-optimization',
    name: '📱 モバイル最適化',
    path: '/mobile-optimization',
    category: '品質',
    description: 'PWA/タッチ操作/通知最適化',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'error-dashboard',
    name: '⚠️ エラーダッシュボード',
    path: '/error-dashboard',
    category: '品質',
    description: 'エラー監視・アラート',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'coverage-report',
    name: '📊 カバレッジレポート',
    path: '/coverage-report',
    category: '品質',
    description: 'テストカバレッジの可視化',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'dev-status',
    name: '🧩 開発ステータス',
    path: '/dev-status',
    category: '品質',
    description: '未実装・モック・WIPの自動検出',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'settings',
    name: '設定',
    path: '/settings',
    category: 'コア',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  // 機能一覧（開発状況） - 管理者のみ閲覧可能
  {
    id: 'features',
    name: '🧭 機能一覧（開発状況）',
    path: '/features',
    category: '機能一覧・進捗',
    description: '機能別の完成状況とアクセス制御',
    status: 'planning',
    requiresRealAPI: false,
  },
  {
    id: 'impulse-countermeasures',
    name: '衝動対策',
    path: '/impulse-countermeasures',
    category: '衝動対策',
    description: '衝動性への対処法・行動設計（プレースホルダー）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  {
    id: 'procrastination-guard',
    name: '先延ばし予防ガード',
    path: '/_bg/procrastination-guard',
    category: '衝動対策',
    description: 'バックグラウンドの先延ばし防止ガード',
    status: 'in_progress',
    requiresRealAPI: false,
    disabled: true,
  },
  {
    id: 'admin',
    name: '管理者ダッシュボード',
    path: '/admin',
    category: '運用',
    description: '管理・運用メトリクス/設定',
    status: 'system_testing',
    requiresRealAPI: true,
  },
  // 管理者ダッシュボード細分化（未完了は非表示）
  {
    id: 'admin-overview',
    name: '管理 概要',
    path: '/admin/overview',
    category: '運用',
    status: 'release_pending',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'admin-users',
    name: '管理 ユーザー',
    path: '/admin/users',
    category: '運用',
    status: 'system_testing',
    requiresRealAPI: true,
    priority: 'P1',
  },
  {
    id: 'admin-actions',
    name: '管理 優先アクション',
    path: '/admin/actions',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
  },
  {
    id: 'admin-analytics',
    name: '管理 分析',
    path: '/admin/analytics',
    category: '運用',
    status: 'system_testing',
    requiresRealAPI: true,
  },
  {
    id: 'admin-errors',
    name: '管理 エラー監視',
    path: '/admin/errors',
    category: '運用',
    status: 'system_testing',
    requiresRealAPI: false,
  },
  {
    id: 'admin-features',
    name: '管理 機能一覧',
    path: '/admin/features',
    category: '運用',
    status: 'system_testing',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'admin-bugs',
    name: '管理 不具合',
    path: '/admin/bugs',
    category: '運用',
    status: 'system_testing',
    requiresRealAPI: true,
    priority: 'P1',
  },
  {
    id: 'admin-settings',
    name: '管理 設定',
    path: '/admin/settings',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
  },
  {
    id: 'admin-assessments',
    name: '管理 診断集計',
    path: '/admin/assessments',
    category: '運用',
    status: 'planning',
    requiresRealAPI: true,
  },
  {
    id: 'admin-learning',
    name: '管理 学習進捗',
    path: '/admin/learning',
    category: '運用',
    status: 'planning',
    requiresRealAPI: true,
  },
  // 管理ヘッダー操作の背景機能
  {
    id: 'admin-refresh',
    name: '管理 更新ボタン',
    path: '/_bg/admin/refresh',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
    disabled: true,
  },
  {
    id: 'admin-approve-next',
    name: '管理 次の段階を承認',
    path: '/_bg/admin/approve-next',
    category: '運用',
    status: 'planning',
    disabled: true,
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'admin-export-report',
    name: '管理 レポート出力',
    path: '/_bg/admin/export-report',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'admin-last-updated',
    name: '管理 最終更新表示',
    path: '/_bg/admin/last-updated',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  {
    id: 'admin-title',
    name: '管理 タイトル表示',
    path: '/_bg/admin/title',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  // 管理ダッシュボード ヘッダーの期間切替（未完了は非表示）
  {
    id: 'admin-window-7d',
    name: '管理 期間切替 7d',
    path: '/_bg/admin/window-7d',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  {
    id: 'admin-window-30d',
    name: '管理 期間切替 30d',
    path: '/_bg/admin/window-30d',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  {
    id: 'admin-window-90d',
    name: '管理 期間切替 90d',
    path: '/_bg/admin/window-90d',
    category: '運用',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
    disabled: true,
  },
  // 個人・ライフスタイル
  {
    id: 'bookshelf',
    name: '📚 本棚',
    path: '/bookshelf',
    category: '個人・ライフスタイル',
    description: '読書記録と本の管理',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'sleep-tracker',
    name: '😴 睡眠トラッカー',
    path: '/sleep-tracker',
    category: '個人・ライフスタイル',
    description: '睡眠パターンの記録と分析',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'quit-smoking',
    name: '🚭 禁煙コーチ',
    path: '/quit-smoking',
    category: '個人・ライフスタイル',
    description: 'AIコーチ・衝動対処・節約可視化',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'impulse-tracker',
    name: '⚡ 衝動トラッカー',
    path: '/impulse-tracker',
    category: '個人・ライフスタイル',
    description: 'ADHD衝動性の記録と管理',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'guitar-practice',
    name: '🎸 ギター練習',
    path: '/guitar-practice',
    category: '個人・ライフスタイル',
    description: 'ギター練習の記録と進捗管理',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'asset-calendar',
    name: '💼 資産カレンダー',
    path: '/asset-calendar',
    category: '個人・ライフスタイル',
    description: '資産管理とイベント計画',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  // 開発・ゲーミフィケーション
  {
    id: 'development-badges',
    name: '🏆 開発バッジ',
    path: '/development-badges',
    category: '開発・ゲーミフィケーション',
    description: '開発実績とバッジの確認',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'ai-gamification',
    name: '🎮 ゲーミフィケーション',
    path: '/ai-gamification',
    category: '開発・ゲーミフィケーション',
    description: 'AI強化ゲーミフィケーション機能',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'gamification',
    name: 'ゲーミフィケーション（ベース）',
    path: '/gamification',
    category: '開発・ゲーミフィケーション',
    description: 'ベース機能/ホームCTA用',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  // 選挙・政治
  {
    id: 'election-candidates',
    name: '🗳️ 選挙候補者',
    path: '/election-candidates',
    category: '選挙・政治',
    description: '選挙候補者一覧と情報',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'candidate-registration',
    name: '📝 候補者登録',
    path: '/candidate-registration',
    category: '選挙・政治',
    description: '新しい候補者の登録',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'district',
    name: '🏛️ 地区情報',
    path: '/district',
    category: '選挙・政治',
    description: '地区別の詳細情報',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'twitter',
    name: '🐦 Twitter',
    path: '/twitter',
    category: '選挙・政治',
    description: 'Twitter統合機能',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'political-trends',
    name: '📈 政治トレンド',
    path: '/political-trends',
    category: '選挙・政治',
    description: '政治動向とトレンド分析',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  // サブスクリプション・請求
  {
    id: 'subscription',
    name: '💳 サブスクリプション',
    path: '/subscription',
    category: 'サブスクリプション・請求',
    description: 'サブスクリプション管理',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P1',
    targetRelease: '2025-09-10',
  },
  {
    id: 'billing-payments',
    name: '課金',
    path: '/subscription',
    category: 'サブスクリプション・請求',
    description: '決済/課金処理（バックエンド連携）',
    status: 'planning',
    requiresRealAPI: true,
    priority: 'P1',
  },
  {
    id: 'subscription-upgrade',
    name: '⭐ アップグレード',
    path: '/subscription-upgrade',
    category: 'サブスクリプション・請求',
    description: 'プレミアムプランへのアップグレード',
    status: 'complete',
    requiresRealAPI: true,
    targetRelease: '2025-09-08',
  },
  {
    id: 'billing-history',
    name: '🧾 請求履歴',
    path: '/billing-history',
    category: 'サブスクリプション・請求',
    description: '過去の請求書と支払い履歴',
    status: 'integration_testing',
    requiresRealAPI: true,
    targetRelease: '2025-09-09',
  },
  {
    id: 'subscription-management',
    name: 'サブスクリプション管理',
    path: '/subscription-management',
    category: 'サブスクリプション・請求',
    description: 'プラン管理・アップグレード・請求設定',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P1',
    targetRelease: '2025-09-10',
  },
  {
    id: 'asset-liability-report',
    name: '📊 資産負債レポート',
    path: '/asset-liability-report',
    category: 'サブスクリプション・請求',
    description: '資産と負債の詳細レポート',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  // プロジェクト管理
  {
    id: 'improvement-plan',
    name: '💡 改善計画',
    path: '/improvement-plan',
    category: 'プロジェクト管理',
    description: 'サイト改善プランの管理',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  // 規約
  {
    id: 'terms-of-service',
    name: '利用規約',
    path: '/docs/terms',
    category: 'コア',
    description: 'サービス利用規約（ドキュメント表示）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P1',
  },
  // ヘッダー領域のUI機能（完了まで非表示）
  {
    id: 'invite-friends',
    name: '友だちを招待',
    path: '/invite',
    category: 'コア',
    description: '紹介リンク共有機能',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'startup-guide',
    name: 'スタートアップガイド',
    path: '/how-it-works',
    category: 'コア',
    description: '3ステップガイド/オンボーディング',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'language-switcher',
    name: '言語切り替え',
    path: '/_bg/language',
    category: 'コア',
    description: '多言語対応UI',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'dark-mode',
    name: 'ダークモード',
    path: '/_bg/dark-mode',
    category: 'コア',
    description: 'テーマ切替',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'notifications',
    name: '通知機能',
    path: '/notifications',
    category: 'コア',
    description: '通知一覧・設定',
    status: 'planning',
    requiresRealAPI: true,
    priority: 'P2',
  },
  {
    id: 'settings-core',
    name: '設定（ヘッダー）',
    path: '/settings',
    category: 'コア',
    description: 'グローバル設定',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'vercel-link',
    name: 'Vercelリンク',
    path: '/_ext/vercel',
    category: 'コア',
    description: '外部リンク（フッター/ヘッダー）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'version-info',
    name: 'バージョン情報',
    path: '/_bg/version-info',
    category: 'コア',
    description: 'ビルド/リリース情報の表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'newsletter-signup',
    name: 'ニュースレター登録',
    path: '/_bg/newsletter',
    category: 'コア',
    description: 'ホームのニュースレター登録CTA',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'home-greeting',
    name: 'ホーム挨拶見出し',
    path: '/_bg/home-greeting',
    category: 'コア',
    description: 'ホームの挨拶（こんにちは/こんばんは 等）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'planning-suggestion',
    name: '計画サジェスト文',
    path: '/_bg/planning-suggestion',
    category: 'コア',
    description: '「まずは優先タスクを1つだけ…」等の誘導文',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'level-badge',
    name: 'レベルバッジ表示',
    path: '/_bg/level-badge',
    category: 'コア',
    description: 'ユーザーレベルのバッジ表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-disclaimer',
    name: 'ヒーロー免責テキスト',
    path: '/_bg/hero-disclaimer',
    category: 'コア',
    description: '「無料・匿名OK・いつでも退会可能」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-headline',
    name: 'ヒーロー見出し',
    path: '/_bg/hero-headline',
    category: 'コア',
    description: '「人生のコントロールを取り戻そう」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-kicker',
    name: 'ヒーロー導入ラベル',
    path: '/_bg/hero-kicker',
    category: 'コア',
    description: '「無料で始める」ラベル',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-subtitle',
    name: 'ヒーロー説明文',
    path: '/_bg/hero-subtitle',
    category: 'コア',
    description: 'ヒーローの長文説明',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-benefit-1',
    name: 'ヒーローベネフィット1',
    path: '/_bg/hero-benefit-1',
    category: 'コア',
    description: '人生の再設計カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-benefit-2',
    name: 'ヒーローベネフィット2',
    path: '/_bg/hero-benefit-2',
    category: 'コア',
    description: '統合管理カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'hero-benefit-3',
    name: 'ヒーローベネフィット3',
    path: '/_bg/hero-benefit-3',
    category: 'コア',
    description: 'AI学習カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'testimonials',
    name: '利用者の声',
    path: '/_bg/testimonials',
    category: 'コア',
    description: 'ユーザー事例・声の表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'weekly-report-preview',
    name: '週次レポート（プレビュー）',
    path: '/_bg/weekly-report',
    category: 'コア',
    description: '週次レポートのプレビュー',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'focus-timer-quick',
    name: '集中タイマー（クイック）',
    path: '/_bg/focus-timer-quick',
    category: 'コア',
    description: 'ホームのクイック集中タイマー',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'stats-today',
    name: '統計: 今日のタスク',
    path: '/_bg/stats-today',
    category: 'コア',
    description: '今日の完了/進捗カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'stats-streak',
    name: '統計: ストリーク',
    path: '/_bg/stats-streak',
    category: 'コア',
    description: '連続日数カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'stats-xp',
    name: '統計: XP',
    path: '/_bg/stats-xp',
    category: 'コア',
    description: '経験値カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'stats-badges',
    name: '統計: バッジ',
    path: '/_bg/stats-badges',
    category: 'コア',
    description: 'バッジカード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'community',
    name: 'コミュニティ機能',
    path: '/community',
    category: 'コア',
    description: 'コミュニティカード/機能',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'quick-add-todo',
    name: 'クイック追加トドボタン',
    path: '/_bg/quick-add-todo',
    category: 'コア',
    description: '右下のクイック追加ボタン',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'app-brand-title',
    name: 'アプリブランド見出し',
    path: '/_bg/app-brand-title',
    category: 'コア',
    description: 'サイドバーの「LifeSync」タイトル',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'app-brand-subtitle',
    name: 'アプリブランドサブタイトル',
    path: '/_bg/app-brand-subtitle',
    category: 'コア',
    description: 'サイドバーの「生産性プラットフォーム」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'daily-nudge',
    name: 'デイリーナッジ（今日の一手）',
    path: '/_bg/daily-nudge',
    category: 'コア',
    description: 'ホームの「今日の一手を作る？」カード',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'nps-inline',
    name: 'NPSインライン調査',
    path: '/_bg/nps-inline',
    category: 'コア',
    description: 'ホーム下部のNPS（0-10）アンケート',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'share-dev-progress',
    name: '開発状況をシェア',
    path: '/_bg/share-dev-progress',
    category: 'コア',
    description: 'Xへ開発状況をシェアするボタン',
    status: 'complete',
    requiresRealAPI: false,
    priority: 'P0',
    targetRelease: '2025-08-31',
  },
  {
    id: 'sidebar-search',
    name: 'サイドバー検索',
    path: '/_bg/sidebar-search',
    category: 'コア',
    description: '「メニューを検索...」入力欄',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'header-page-title',
    name: 'ヘッダーページタイトル',
    path: '/_bg/header-page-title',
    category: 'コア',
    description: 'ヘッダーの「ダッシュボード」見出し',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'breadcrumbs',
    name: 'パンくず',
    path: '/_bg/breadcrumbs',
    category: 'コア',
    description: 'ホーム › トップ などのパンくず',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'footer-security-banner',
    name: 'フッターセキュリティバナー',
    path: '/_bg/footer-security-banner',
    category: 'コア',
    description: '「通信は暗号化...システム稼働状況・セキュリティ方針」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'system-status',
    name: 'システム稼働状況',
    path: '/status',
    category: 'コア',
    description: 'ステータスページへのリンク/画面',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'security-policy',
    name: 'セキュリティ方針',
    path: '/security',
    category: 'コア',
    description: 'セキュリティポリシーの表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'terms',
    name: '利用規約（フッターリンク）',
    path: '/terms',
    category: 'コア',
    description: 'フッターの「利用規約」リンク/画面',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'contact',
    name: 'お問い合わせ',
    path: '/contact',
    category: 'コア',
    description: 'お問い合わせページ/リンク',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'header-user-info',
    name: 'ヘッダーユーザー情報',
    path: '/_bg/header-user-info',
    category: 'コア',
    description: 'ヘッダー右の表示名/メールの表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P1',
  },
  {
    id: 'how-it-works',
    name: 'How It Works セクション',
    path: '/_bg/how-it-works',
    category: 'コア',
    description: 'ホームのHow It Works全体',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'quick-actions-section',
    name: 'クイックアクション セクション',
    path: '/_bg/quick-actions',
    category: 'コア',
    description: 'ホームのクイックアクション見出しとグリッド',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'ai-enhancements-card',
    name: 'AI強化機能カード',
    path: '/_bg/ai-enhancements',
    category: 'コア',
    description: 'ホームのAI強化カード（説明/CTA）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'ai-gamification-core',
    name: 'AIゲーミフィケーション（概要）',
    path: '/_bg/ai-gamification',
    category: 'AI & アシスタント',
    description: 'AIで強化されたゲーミフィケーション体験（背景要素）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'bottom-cta-heading',
    name: 'ボトムCTA見出し',
    path: '/_bg/bottom-cta-heading',
    category: 'コア',
    description: '「今日からはじめよう」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'bottom-tagline',
    name: 'ボトムCTAタグライン',
    path: '/_bg/bottom-tagline',
    category: 'コア',
    description: '「AI秘書と自己診断で、最短60秒の一歩から。」',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'learning-streak',
    name: '学習ストリーク',
    path: '/_bg/learning-streak',
    category: 'コア',
    description: '今週の学習ストリーク表示',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'wbs-creator',
    name: '📊 WBSクリエイター',
    path: '/wbs-creator',
    category: 'プロジェクト管理',
    description: 'ワークブレイクダウン構造作成',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'bug-new',
    name: '🐞 不具合登録',
    path: '/bugs/new',
    category: 'プロジェクト管理',
    description: '機能に紐づく不具合の登録',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  // ユーザー・設定
  {
    id: 'profile',
    name: '👤 プロフィール',
    path: '/profile',
    category: 'ユーザー・設定',
    description: 'ユーザープロフィール設定',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  // 認証・アカウント
  {
    id: 'login',
    name: 'ログイン',
    path: '/login',
    category: 'ユーザー・設定',
    description: 'サインイン（メール/外部IdP）',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P0',
    targetRelease: '2025-09-01',
  },
  {
    id: 'user-registration',
    name: 'ユーザー登録',
    path: '/register',
    category: 'ユーザー・設定',
    description: '新規アカウント作成',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P0',
    targetRelease: '2025-09-03',
  },
  {
    id: 'logout',
    name: 'ログアウト',
    path: '/_bg/logout',
    category: 'ユーザー・設定',
    description: 'セッション終了（バックグラウンド機能）',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P0',
    targetRelease: '2025-09-02',
  },
  // 生産性
  {
    id: 'game-loop-tasks',
    name: 'ゲームループタスク',
    path: '/game-loop-tasks',
    category: '生産性',
    description: 'プロシージネーション対策・自動タスク分解・マイクロタスク管理',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'todos-legacy',
    name: '従来タスク',
    path: '/todos',
    category: '生産性',
    description: '標準ToDo管理・チェックリスト',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'task-management',
    name: 'タスク管理',
    path: '/task-management',
    category: '生産性',
    description: 'タスク一覧・編集・管理',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  // 分析・レポート
  {
    id: 'badge-completion',
    name: 'バッジ完了予測',
    path: '/badge-completion',
    category: '分析・レポート',
    description: 'AI駆動バッジ完了予測',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'badge-showcase',
    name: 'バッジショーケース',
    path: '/badge-showcase',
    category: '分析・レポート',
    description: '実績展示・共有機能',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  // 自動化
  {
    id: 'automation-rules',
    name: '自動化ルール',
    path: '/automation-rules',
    category: '自動化',
    description: 'システム自動化・ルール設定',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'multi-ai',
    name: 'AI統合',
    path: '/multi-ai',
    category: '自動化',
    description: 'AI機能統合・複数AI連携',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'diary',
    name: '📖 日記',
    path: '/diary',
    category: '個人',
    description: '日々の記録と振り返り',
    status: 'in_progress',
    requiresRealAPI: false,
  },
  {
    id: 'blog',
    name: '📝 ブログ',
    path: '/blog',
    category: 'コンテンツ',
    description: 'ブログ記事一覧・投稿',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'cognitive-finance',
    name: '💰 認知最適化財務管理',
    path: '/cognitive-finance',
    category: '財務',
    description: 'ADHD/ASD特性に配慮した資産管理',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'beta-user-recruitment',
    name: '🌟 ベータユーザー募集',
    path: '/beta-user-recruitment',
    category: '運用',
    description: '開発参加・フィードバック募集',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  {
    id: 'user-testing',
    name: '🧪 実ユーザーテスト',
    path: '/user-testing',
    category: '品質',
    description: 'ユーザビリティテスト・品質検証',
    status: 'in_progress',
    requiresRealAPI: true,
  },
  // ===== Newly discovered features from routes (auto-registered) =====
  {
    id: 'docs-viewer',
    name: '📄 ドキュメント',
    path: '/docs',
    category: '品質',
    description: 'Markdownドキュメントビューア',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'pricing',
    name: '💵 料金プラン',
    path: '/pricing',
    category: 'サブスクリプション・請求',
    description: 'プランと価格の案内',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'changelog',
    name: '📝 変更履歴',
    path: '/changelog',
    category: 'コア',
    description: 'バージョン履歴と変更点',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'privacy',
    name: 'プライバシー',
    path: '/privacy',
    category: 'コア',
    description: 'プライバシーポリシー',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'onboarding',
    name: 'オンボーディング',
    path: '/onboarding',
    category: 'コア',
    description: '初回利用ガイド',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'iq-test',
    name: '🧠 IQテスト',
    path: '/iq-test',
    category: '診断',
    description: 'IQテスト',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'mbti-test',
    name: '🧠 MBTIテスト',
    path: '/mbti-test',
    category: '診断',
    description: 'MBTI性格診断',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'firebase-login',
    name: 'Firebaseログイン',
    path: '/firebase-login',
    category: 'ユーザー・設定',
    description: 'Firebase認証（検証用）',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'forgot-password',
    name: 'パスワードをお忘れですか',
    path: '/forgot-password',
    category: 'ユーザー・設定',
    description: 'パスワードリセットメール送信',
    status: 'planning',
    requiresRealAPI: true,
    priority: 'P1',
    targetRelease: '2025-09-04',
  },
  {
    id: 'reset-password',
    name: 'パスワード再設定',
    path: '/reset-password',
    category: 'ユーザー・設定',
    description: 'パスワード再設定画面',
    status: 'planning',
    requiresRealAPI: true,
    priority: 'P1',
    targetRelease: '2025-09-05',
  },
  {
    id: 'notification-settings',
    name: '通知設定',
    path: '/settings/notifications',
    category: 'ユーザー・設定',
    description: '通知の個別設定',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'kpi-naming-rules',
    name: 'KPI命名規則',
    path: '/kpi-naming-rules',
    category: '品質',
    description: 'KPI命名ガイド',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'analytics-dashboard-feature',
    name: 'アナリティクスダッシュボード',
    path: '/analytics-dashboard',
    category: '分析',
    description: '主要メトリクスのダッシュボード',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'testing-dashboard',
    name: 'テストダッシュボード',
    path: '/testing-dashboard',
    category: '品質',
    description: 'テスト状況の可視化',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'sns-share',
    name: 'SNS共有',
    path: '/sns-share',
    category: 'コア',
    description: 'SNS共有機能',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'bug-list',
    name: '🐞 不具合一覧',
    path: '/bugs',
    category: 'プロジェクト管理',
    description: '不具合の一覧と管理',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P1',
    targetRelease: '2025-09-07',
  },
  {
    id: 'improvement-implementation',
    name: '改善実装',
    path: '/improvement-implementation',
    category: 'プロジェクト管理',
    description: '改善計画の実装トラッキング',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  // モバイル対応・開発向け/運用向け機能
  {
    id: 'mobile-tab-bar',
    name: 'モバイルタブバー',
    path: '/_bg/mobile-tab-bar',
    category: '品質',
    description: 'モバイル下部タブナビ',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'mobile-responsive-core',
    name: 'モバイルレスポンシブ基盤',
    path: '/_bg/mobile-responsive-core',
    category: '品質',
    description: 'ブレークポイント/安全領域対応',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'client-error-reporting',
    name: 'クライアントエラーレポート',
    path: '/_bg/client-error-reporting',
    category: '品質',
    description: 'フロントエンドの自動/手動報告',
    status: 'complete',
    requiresRealAPI: true,
    priority: 'P1',
  },
  {
    id: 'server-error-reporting',
    name: 'サーバエラーレポート',
    path: '/_bg/server-error-reporting',
    category: '運用',
    description: 'サーバ側のエラー収集/集約',
    status: 'planning',
    requiresRealAPI: true,
    priority: 'P1',
  },
  {
    id: 'debug-logging',
    name: 'デバッグログ出力',
    path: '/_bg/debug-logging',
    category: '品質',
    description: '開発向け詳細ログ出力',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'dev-logging-console',
    name: '開発コンソールビューア',
    path: '/_bg/dev-logging-console',
    category: '品質',
    description: 'UIでログを閲覧/フィルタ',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P3',
  },
  {
    id: 'sse-health-monitor',
    name: 'SSEヘルスモニタ',
    path: '/_bg/sse-health-monitor',
    category: '運用',
    description: '通知SSEの死活監視',
    status: 'planning',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'rate-limiting',
    name: 'レート制限',
    path: '/_bg/rate-limiting',
    category: '運用',
    description: 'APIレート制限の設定/管理',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'cors-config',
    name: 'CORS設定',
    path: '/_bg/cors',
    category: '運用',
    description: 'CORSポリシーの設定',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
  {
    id: 'error-recovery-service',
    name: 'エラー回復サービス',
    path: '/_bg/error-recovery-service',
    category: '運用',
    description: '自動回復/自己診断/監視',
    status: 'in_progress',
    requiresRealAPI: false,
    priority: 'P2',
  },
];

const ALLOWLIST_PATHS: string[] = [
  '/',
  '/home',
  '/features',
  '/sitemap',
  '/docs',
  '/login',
  '/register',
  '/privacy',
  '/changelog',
  '/how-it-works',
  '/invite',
];

export function getFeatureByPath(pathname: string): Feature | undefined {
  const match = featuresRegistry.find(
    (f) => pathname === f.path || pathname.startsWith(f.path + '/')
  );
  return match;
}

export function isFeatureAccessible(pathname: string): {
  allowed: boolean;
  reason?: string;
  feature?: Feature;
} {
  if (ALLOWLIST_PATHS.some((p) => pathname === p || pathname.startsWith(p + '/'))) {
    return { allowed: true };
  }
  const feature = getFeatureByPath(pathname);
  if (!feature) return { allowed: true };
  if ((feature as any).disabled) {
    return { allowed: false, reason: '無効化された機能です', feature };
  }
  // アクセス許可: 完成 or 試験段階（結合/総合/リリース待ち）
  const allowedStatuses = new Set<FeatureStatus>([
    'complete',
    'integration_testing',
    'system_testing',
    'release_pending',
  ]);
  if (!allowedStatuses.has(feature.status)) {
    return { allowed: false, reason: '未完成の機能です', feature };
  }
  if (feature.requiresRealAPI && USE_MOCK_DATA) {
    return { allowed: false, reason: 'モックAPIモードでは利用できません', feature };
  }
  return { allowed: true, feature };
}
